'use client';
import Link from 'next/link';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { api } from '@/lib/client';
import PhoneAuth, { AuthTabs } from './PhoneAuth';
const titles:Record<string,string>={login:'С возвращением',register:'Расскажите о своём месте',forgot:'Восстановить пароль',reset:'Новый пароль',verify:'Подтвердить почту',resend:'Отправить письмо повторно'};
export default function AuthForm({mode,token}:{mode:string;token:string}) {const router=useRouter();const [error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState<'email'|'phone'>('email');
 // Вход по номеру телефона доступен на тех же страницах: почта и SMS — два равноправных способа.
 const tabbed=['login','register','forgot'].includes(mode);
 if(tabbed&&tab==='phone')return <div className="auth-wrap"><PhoneAuth mode={mode} onEmail={()=>setTab('email')}/></div>;
 return <div className="auth-wrap"><form className="form-card" onSubmit={async e=>{e.preventDefault();setError('');setBusy(true);const fields=Object.fromEntries(new FormData(e.currentTarget));try{const result=await api(`auth/${mode}`,{...fields,token});if(result.redirect){router.push(result.redirect);router.refresh();}else setMessage(result.message||(mode==='verify'?'Почта подтверждена. Теперь можно отправить объект на модерацию.':'Пароль изменён. Войдите с новым паролем.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><span className="eyebrow">КАБИНЕТ МЕСТНОГО БИЗНЕСА</span><div><h1>{titles[mode]}</h1><p>{mode==='register'?'Создайте аккаунт, чтобы добавить объект в каталог.':'Управляйте объектами и помогайте гостям найти вас.'}</p></div>{tabbed&&<AuthTabs value="email" onChange={setTab}/>}{message?<><div className="notice" role="status">{message}</div><Link className="button" href="/auth/login">Перейти ко входу</Link></>:<>{!['verify','reset'].includes(mode)&&<label>Email<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label>}{['login','register','reset'].includes(mode)&&<label>Пароль<input name="password" type="password" minLength={10} maxLength={72} required autoComplete={mode==='login'?'current-password':'new-password'} placeholder="Не менее 10 символов"/></label>}{mode==='verify'&&<p>Нажмите кнопку, чтобы подтвердить этот адрес электронной почты. Ссылка действует один час.</p>}{mode==='register'&&<label className="checkbox"><input type="checkbox" required/><span>Я ознакомился с <Link href="/privacy" target="_blank" style={{textDecoration:'underline'}}>политикой конфиденциальности</Link></span></label>}{error&&<p className="error-message" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?'Подождите…':{login:'Войти',register:'Создать аккаунт',forgot:'Отправить ссылку',reset:'Сохранить пароль',verify:'Подтвердить email',resend:'Отправить письмо'}[mode]}</button></>}<div className="auth-links"><Link href={mode==='login'?'/auth/register':'/auth/login'}>{mode==='login'?'Создать аккаунт':'Уже есть аккаунт? Войти'}</Link><Link href="/auth/forgot">Забыли пароль?</Link></div></form></div>;}
