import Link from 'next/link';
import { ArrowUpRight, Clock3, ArrowRight, BookOpen } from 'lucide-react';
import type { Article } from '@/lib/types';
import { articleUrl, readingMinutes, sectionLabels, areaLabels } from '@/lib/editorial';
import { dateLabel } from '@/lib/data';
export function EditorialCard({article,index}:{article:Article;index?:number}) {return <Link className="editorial-card" href={articleUrl(article)}><div className="editorial-card-image">{article.cover?<img src={article.cover} alt={article.photoCredit?.caption||article.title} loading="lazy" width={800} height={530}/>:<div className="image-placeholder"><BookOpen size={45}/></div>}<span className="editorial-chip">{article.kind==='news'?'Новости':article.area?areaLabels[article.area]:sectionLabels[article.section||'tips']}</span>{index!==undefined&&<span className="editorial-number">{String(index+1).padStart(2,'0')}</span>}</div><div className="editorial-card-content"><div className="editorial-meta">{article.kind==='news'&&article.sourcePublishedAt?<time dateTime={article.sourcePublishedAt}>{dateLabel(article.sourcePublishedAt)}</time>:<span><Clock3 size={13}/>{readingMinutes(article.body)} мин чтения</span>}<ArrowUpRight size={18}/></div><h3>{article.title}</h3><p>{article.summary}</p><span className="editorial-read">{article.kind==='news'?'Что произошло':'Читать материал'} <ArrowRight size={15}/></span></div>{article.photoCredit&&<span className="editorial-card-author">Фото: {article.photoCredit.author} · {article.photoCredit.license}</span>}</Link>;}
export function ArticleBody({body}:{body:string}) {return <div className="article-prose">{body.split(/\n\s*\n/).map((block,i)=>{if(block.startsWith('## '))return <h2 id={`section-${i}`} key={i}>{block.slice(3)}</h2>;if(block.split('\n').every(l=>l.startsWith('- ')))return <ul key={i}>{block.split('\n').map((l,j)=><li key={j}>{l.slice(2)}</li>)}</ul>;return <p key={i}>{block}</p>;})}</div>;}
export function Contents({body}:{body:string}) {const sections=body.split(/\n\s*\n/).map((block,i)=>({block,i})).filter(s=>s.block.startsWith('## '));if(!sections.length)return null;return <nav className="article-toc" aria-label="Содержание статьи"><span className="eyebrow">В ЭТОМ МАТЕРИАЛЕ</span>{sections.map(({block,i})=><a href={`#section-${i}`} key={i}>{block.slice(3)}</a>)}<Link className="text-link" href="/sights">Что ещё посмотреть <ArrowUpRight size={15}/></Link></nav>;}
export function PhotoAttribution({article}:{article:Article}) {const credit=article.photoCredit;if(!credit)return null;return <figcaption className="photo-attribution">{credit.caption}. Фото: <a href={credit.source} target="_blank" rel="noopener noreferrer">{credit.author}</a> · <a href={credit.licenseUrl} target="_blank" rel="noopener noreferrer">{credit.license}</a>. {credit.changes}.</figcaption>;}
