import { getTranslator } from '@/lib/i18n/server';
import Link from 'next/link';
import { ArrowUpRight, Clock3, ArrowRight, BookOpen } from 'lucide-react';
import type { Article } from '@/lib/types';
import { articleUrl, readingMinutes, sectionLabels, areaLabels } from '@/lib/editorial';
import { dateLabel } from '@/lib/data';
export async function EditorialCard({article,index}:{article:Article;index?:number}) {const translate=await getTranslator();return <Link className="editorial-card" href={articleUrl(article)}><div className="editorial-card-image">{translate(article.cover?<img src={article.cover} alt={translate(article.photoCredit?.caption||article.title)} loading="lazy" width={800} height={530}/>:<div className="image-placeholder"><BookOpen size={45}/></div>)}<span className="editorial-chip">{translate(article.kind==='news'?'Новости':article.area?areaLabels[article.area]:sectionLabels[article.section||'tips'])}</span>{translate(index!==undefined&&<span className="editorial-number">{translate(String(index+1).padStart(2,'0'))}</span>)}</div><div className="editorial-card-content"><div className="editorial-meta">{translate(article.kind==='news'&&article.sourcePublishedAt?<time dateTime={article.sourcePublishedAt}>{translate(dateLabel(article.sourcePublishedAt))}</time>:<span><Clock3 size={13}/>{translate(readingMinutes(article.body))}{translate(" мин чтения")}</span>)}<ArrowUpRight size={18}/></div><h3>{translate(article.title)}</h3><p>{translate(article.summary)}</p><span className="editorial-read">{translate(article.kind==='news'?'Что произошло':'Читать материал')} <ArrowRight size={15}/></span></div>{translate(article.photoCredit&&<span className="editorial-card-author">{translate("Фото: ")}{translate(article.photoCredit.author)} · {translate(article.photoCredit.license)}</span>)}</Link>;}
export async function ArticleBody({body}:{body:string}) {const translate=await getTranslator();return <div className="article-prose">{translate(body.split(/\n\s*\n/).map((block,i)=>{if(block.startsWith('## '))return <h2 id={`section-${i}`} key={i}>{translate(block.slice(3))}</h2>;if(block.split('\n').every(l=>l.startsWith('- ')))return <ul key={i}>{translate(block.split('\n').map((l,j)=><li key={j}>{translate(l.slice(2))}</li>))}</ul>;return <p key={i}>{translate(block)}</p>;}))}</div>;}
export async function Contents({body}:{body:string}) {const translate=await getTranslator();const sections=body.split(/\n\s*\n/).map((block,i)=>({block,i})).filter(s=>s.block.startsWith('## '));if(!sections.length)return null;return <nav className="article-toc" aria-label={translate("Содержание статьи")}><span className="eyebrow">{translate("В ЭТОМ МАТЕРИАЛЕ")}</span>{translate(sections.map(({block,i})=><a href={`#section-${i}`} key={i}>{translate(block.slice(3))}</a>))}<Link className="text-link" href="/sights">{translate("Что ещё посмотреть ")}<ArrowUpRight size={15}/></Link></nav>;}
export async function PhotoAttribution({article}:{article:Article}) {const translate=await getTranslator();const credit=article.photoCredit;if(!credit)return null;return <figcaption className="photo-attribution">{translate(credit.caption)}{translate(". Фото: ")}<a href={credit.source} target="_blank" rel="noopener noreferrer">{translate(credit.author)}</a> · <a href={credit.licenseUrl} target="_blank" rel="noopener noreferrer">{translate(credit.license)}</a>. {translate(credit.changes)}.</figcaption>;}
