'use client';
import { useTranslator } from '@/components/LocaleProvider';

import { useEffect, useState } from 'react';
import { Phone, MessageCircle, Navigation, ExternalLink, Mountain } from 'lucide-react';
import { api } from '@/lib/client';
import type { PublicListing, Photo } from '@/lib/types';
export function Gallery({photos,title}:{photos:Photo[];title:string}) {const translate=useTranslator();const [selected,setSelected]=useState(0);if(!photos.length)return <div className="image-placeholder gallery-placeholder"><Mountain size={70}/><span>{translate("Владелец пока не добавил фотографии")}</span></div>;return <div><img className="gallery-main" src={photos[selected].url} alt={translate(photos[selected].caption||title)}/>{translate(photos[selected].caption&&<p className="form-help" style={{marginTop:10}}>{translate(photos[selected].caption)}</p>)}{translate(photos.length>1&&<div className="gallery-thumbs">{translate(photos.map((photo,i)=><button type="button" aria-label={translate(`Фото ${i+1}: ${photo.caption||title}`)} aria-pressed={selected===i} className={selected===i?'selected':''} key={photo.url} onClick={()=>setSelected(i)}><img src={photo.url} alt=""/></button>))}</div>)}</div>;}
export function Contacts({item}:{item:PublicListing}) {const translate=useTranslator();useEffect(()=>{void api('event',{id:item.id,type:'view'}).catch(()=>{});},[item.id]);const track=(type:string)=>{void api('event',{id:item.id,type}).catch(()=>{});};return <>{translate(item.phone&&<a className="button" href={`tel:${item.phone.replace(/[^+\d]/g,'')}`} onClick={()=>track('phone')}><Phone size={18}/>{translate("Позвонить")}</a>)}{translate(item.whatsapp&&<a className="button secondary" target="_blank" rel="noopener noreferrer" href={`https://wa.me/${item.whatsapp.replace(/\D/g,'')}`} onClick={()=>track('whatsapp')}><MessageCircle size={18}/>{translate("Написать в WhatsApp")}</a>)}{translate(!item.demo&&item.lat!==null&&item.lng!==null&&<a className="button secondary" href={`https://www.google.com/maps/dir/?api=1&destination=${item.lat},${item.lng}`} target="_blank" rel="noopener noreferrer" onClick={()=>track('route')}><Navigation size={18}/>{translate("Построить маршрут")}</a>)}{translate(item.website&&<a className="text-link" href={item.website} target="_blank" rel="noopener noreferrer">{translate("Сайт объекта ")}<ExternalLink size={15}/></a>)}{translate(item.social&&<a className="text-link" href={item.social} target="_blank" rel="noopener noreferrer">{translate("Социальные сети ")}<ExternalLink size={15}/></a>)}{translate(!item.phone&&!item.whatsapp&&!item.website&&!item.social&&<p>{translate("Владелец пока не указал контакты.")}</p>)}</>;}
export function Report({slug}:{slug:string}) {const translate=useTranslator();const [message,setMessage]=useState(''),[error,setError]=useState(''),[sent,setSent]=useState(false),[busy,setBusy]=useState(false);return <details className="report-form"><summary>{translate("Сообщить о неточности")}</summary>{translate(sent?<p className="notice">{translate("Спасибо! Сообщение передано администратору.")}</p>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('report',{slug,message});setSent(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>{translate("Что нужно исправить?")}<textarea required minLength={10} maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)}/></label>{translate(error&&<p className="error-message" role="alert">{translate(error)}</p>)}<button disabled={busy} className="button secondary">{translate(busy?'Отправляем…':'Отправить сообщение')}</button></form>)}</details>;}
