import { getTranslator } from '@/lib/i18n/server';
import Link from 'next/link';
import { Map, ArrowRight } from 'lucide-react';
import { catalog, taxonomy } from '@/lib/data';
import Filters from '@/components/Filters';
import CategoryNav from '@/components/CategoryNav';
import { ListingCard, Empty, PageTitle } from '@/components/UI';
export const metadata={title:'Места и услуги',description:'Найдите проживание, кафе, экскурсии и прокат в Каркаралинске.',alternates:{canonical:'/catalog'}};
export default async function Catalog({searchParams}:{searchParams:Promise<Record<string,string>>}) {const translate=await getTranslator();const params=await searchParams;const [{items,total,page,pages},tax]=await Promise.all([catalog(params),taxonomy()]);return <div className="container page"><PageTitle eyebrow={translate("ОТДЫХ В ВАШЕМ РИТМЕ")} title={translate("Места и услуги")} text={translate("Найдите то, что сделает вашу поездку особенной.")}/><CategoryNav tax={tax} params={params}/><div className="catalog-layout"><aside><Filters key={new URLSearchParams(params).toString()} tax={tax} params={params}/></aside><div className="catalog-results"><div className="results-toolbar"><span>{translate("Найдено мест: ")}<strong>{translate(total)}</strong></span><Link className="button secondary small" href={`/map?${new URLSearchParams(params)}`}><Map size={17}/>{translate("На карте")}</Link></div>{translate(items.length?<div className="listing-grid catalog-grid">{translate(items.map(item=><ListingCard key={item.id} item={item} categories={tax}/>))}</div>:<Empty title={translate("Ничего не найдено")} text={translate("Попробуйте изменить запрос или сбросить фильтры.")} reset/>)}{translate(pages>1&&<nav className="pagination" aria-label={translate("Страницы каталога")}>{translate(page>1&&<Link className="button secondary" href={`?${new URLSearchParams({...params,page:String(page-1)})}`}>{translate("Назад")}</Link>)}<span>{translate(page)} / {translate(pages)}</span>{translate(page<pages&&<Link className="button secondary" href={`?${new URLSearchParams({...params,page:String(page+1)})}`}>{translate("Далее ")}<ArrowRight size={17}/></Link>)}</nav>)}</div></div></div>;}
