import { getTranslator } from '@/lib/i18n/server';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { MapPin, Check, ChevronRight } from 'lucide-react';
import { publicListing, taxonomy, priceLabel, dateLabel } from '@/lib/data';
import Gallery from '@/components/PlaceGallery';
import { Contacts, Report } from '@/components/PlaceActions';
import MapView from '@/components/MapView';
import styles from './place.module.css';
export async function generateMetadata({params}:{params:Promise<{slug:string}>}) {const {slug}=await params;const item=await publicListing(slug);return {title:item?.title||'Место не найдено',description:item?.description.slice(0,160),robots:item?.demo?{index:false,follow:true}:undefined,alternates:{canonical:`/places/${slug}`}};}
export default async function Place({params}:{params:Promise<{slug:string}>}) {const translate=await getTranslator();const {slug}=await params;const item=await publicListing(slug);if(!item)notFound();const tax=await taxonomy();const stale=!!item.confirmedAt&&Date.now()-new Date(item.confirmedAt).getTime()>Number(process.env.STALE_DAYS||60)*86400000;return <div className="container page"><div className="breadcrumbs"><Link href="/">{translate("Главная")}</Link><ChevronRight size={14}/><Link href="/catalog">{translate("Места и услуги")}</Link><ChevronRight size={14}/><span>{translate(item.title)}</span></div><div className="detail-header"><span className="eyebrow">{translate(tax.find(t=>t._id===item.category)?.name)}</span><h1>{translate(item.title)}</h1><p className="location"><MapPin size={17}/>{translate(item.address)}</p>{translate(item.demo&&<p className="notice warning">{translate("Демонстрационный объект. Название и точка на карте вымышлены. Это пример карточки, а не реальное предложение; координаты не предназначены для навигации.")}</p>)}</div><div className={styles.layout}><div className={styles.gallery}><Gallery photos={item.photos} title={translate(item.title)}/></div><div className={styles.content}><section className="detail-section"><h2>{translate("О месте")}</h2><p className="prose">{translate(item.description)}</p></section>{translate(!!item.amenities.length&&<section className="detail-section"><h2>{translate("Услуги и удобства")}</h2><div className="amenity-tags">{translate(item.amenities.map(a=><span key={a}><Check size={15}/>{translate(a)}</span>))}</div></section>)}{translate(item.conditions&&<section className="detail-section"><h2>{translate("Условия посещения")}</h2><p className="prose">{translate(item.conditions)}</p></section>)}{translate(item.hours&&<section className="detail-section"><h2>{translate("Время работы и сезонность")}</h2><p className="prose">{translate(item.hours)}</p></section>)}{translate(item.lat!==null&&item.lng!==null&&<section className="detail-section detail-map"><h2>{translate(item.demo?'Условная точка на карте':'Как добраться')}</h2><p>{translate(item.address)}</p><MapView items={[item]}/></section>)}<Report slug={slug}/></div><aside className={`contact-card ${styles.contact}`}><strong className="contact-price">{translate(priceLabel(item))}</strong><p>{translate("Уточняйте условия и доступность напрямую у представителя.")}</p><Contacts item={item}/><div className={`notice ${stale?'warning':''}`}>{translate(item.confirmedAt?`Информация подтверждена ${dateLabel(item.confirmedAt)}`:'Владелец пока не подтвердил актуальность информации.')}{translate(stale&&<><br/>{translate("Информация давно не обновлялась — уточните условия.")}</>)}</div></aside></div></div>;}
